### ISSUE TITLE
Support multiple rust users

### ISSUE THREAD

**Issue by chasinglogic** [hurricanehrndz/ansible-rustup#1]
Something like:

```yaml
rust_users:
   - user1
   - user2
```

Should be possible ideally

**Comment by hurricanehrndz** [comment]
Great suggestion!

**Comment by hurricanehrndz** [comment]
You can use Ansible's built in loop function:
https://stackoverflow.com/questions/33415992/ansible-how-to-iterate-over-a-role-with-an-array
