### ISSUE TITLE
Is the custom shell integration still relevant?

### ISSUE THREAD

**Issue by guenhter** [hurricanehrndz/ansible-rustup#17]
Hi,

as already discussed in last weeks PR: Do you think the shell integration done in this role has advantages over the one which is already done by the rustup installation? 
If it has no advantage, do you think it should get removed here to make the role easier?

kind regards

**Comment by hurricanehrndz** [comment]
Once I get the test back up and running I will be ready to decide. What particular part of the shell integration do you find difficult?

This role was originally developed as part of my dotfiles deployment. In such a scenario there were are benefits to opting out of the installers shell integration and moving the logic to ansible

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Günther Grill ***@***.***>
Sent: Monday, May 15, 2023 5:23:33 AM
To: hurricanehrndz/ansible-rustup ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hurricanehrndz/ansible-rustup] Is the custom shell integration still relevant? (Issue #17)


Hi,

as already discussed in last weeks PR: Do you think the shell integration done in this role has advantages over the one which is already done by the rustup installation?
If it has no advantage, do you think it should get removed here to make the role easier?

kind regards

**Comment by guenhter** [comment]
I don't find it difficult at all, it was just irritating when I turned off shell-integration, in the role that the integration is then anyway done by rustup. When I found out what was going on, I asked myself this question which I share here with you.

**Comment by hurricanehrndz** [comment]
The install command may need to be updated so that the installer avoids touching any shell files

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guenhter** [comment]
Then maybe the question arises: If the installer is already capable of doing the shell integration, why isn't this then just reused?

**Comment by hurricanehrndz** [comment]
fair enough! Let me get the tests going, I got a lot on my plate, but will try to get to it.

**Comment by guenhter** [comment]
Hi, any update on this?

**Comment by hurricanehrndz** [comment]
Thanks for checking back in on this. I have some free time this week. So this we be one of my top priorities.

I agree with you that double shell integration is unwanted. Is the ability to disable shell integration important?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guenhter** [comment]
We already disabled the CLI integration of this ansible role and use the CLI integration of the rustup directly.
So we are already happy as it is, I just wanted do check with you if this role could be made easier by removing the CLI integration of this role and just use rustup. If you for some reason think the CLI integration of this role is beneficial, it is perfectly fine and we close this issue.

**Comment by hurricanehrndz** [comment]
Let’s drop it then, cause I haven’t seen any new issues since the last change. If you do the PR I will merge it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guenhter** [comment]
Nice. I'll prepare the PR sometime next week. I like to see code getting smaller and simpler :)
