### ISSUE TITLE
If we run this against the same host twice, rustup_shell_rc_settings_file ends up incorrect for the second run

### ISSUE THREAD

**Issue by Zorlin** [hurricanehrndz/ansible-rustup#19]
Hi there,

There's a bug in this module. because we only check that rustup_shell_rc_settings_file is *defined*, not that it is *correct*.

 I had to patch my own hacky version together in https://github.com/Zorlin/ansible-rustup/commit/fe7f72e9ff598fe710c7513e20803deec3df97e2

The effect of this is that if I run against, say, rustup_user: lotus and then later try and do rustup_user: boost, it tries to write to /home/lotus/.bashrc which fails.

**Comment by hurricanehrndz** [comment]
Let's drop the rc settings

**Comment by hurricanehrndz** [comment]
https://github.com/hurricanehrndz/ansible-rustup/pull/18
